name: FungiScan
description: "Mushroom Identifier App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  image: ^4.5.4
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  hive: ^2.2.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  flutter_floating_bottom_bar: ^1.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/.
    - assets/error.jpg
    - assets/labels.txt
    - assets/mushroom_info.json
    - .env
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_logo.png"
  min_sdk_android: 21