name: mushroom_identifier
description: "Mushroom Identifier App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  image: ^4.5.4
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/.
    - assets/sample/error.jpg
    - assets/sample/sample.jpg
    - assets/models/mushroom_efficientnet_lite2.pt
    - assets/models/mushroom_mobilenetv2.pt
    - assets/labels.txt
    - .env
  uses-material-design: true